### ISSUE TITLE
Open files from yazi in a helix buffer instead of a zellij new pane

### ISSUE THREAD

**Issue by luccahuguet** [luccahuguet/zellij#8]
No idea how to do that, but things I think of, I'll document here

**Comment by adriangalilea** [comment]
This is what I'm looking for

**Comment by luccahuguet** [comment]
> This is what I'm looking for

This should be unblocked once helix's plugin system is first released (in six to 9 months), so someone could create a plugin that enables that 

but at the same time, we should be getting a file tree plugin, so it is not clear whether having a "yazi sidebar" would still be of value... Why would we not use helix's own file tree plugin? 

🤔

**Comment by luccahuguet** [comment]
if this is possible sooner, i shall implement it!

**Comment by adriangalilea** [comment]
https://github.com/user-attachments/assets/a9dc9820-48d7-4f74-9a3a-413c8c7eeeb3
_Running this on a pi zero through ssh, hence why it's struggling._

As seen in [this github issue](https://github.com/zellij-org/zellij/issues/3018#issuecomment-2099408250) you can make it load in the current buffer, you can even select multiple files.

I think the ideal workflow is:

- side-panel that is hid by default.
- <kbd>alt</kbd>+<kbd>f</kbd> to show it
  - <kbd>esc</kbd> to close it
  - <kbd>enter</kbd> to move the selected files into the buffer and hid the side-panel again.
  
That way the file-tree can be inspected easily with a keybind that you can easily close again, so you can use it both for having a view as well as selecting the files.

I believe this is possible to do as of now, but I won't bother since my current workflow is good enough for me, and I rather work that continue tinkering atm :)

**Comment by luccahuguet** [comment]
Awesome! Looks very cool. 

I will probably point to your solution in the readme, I bet it will help many people

I might take a stab at doing this with nushell

thank you for taking the time

**Comment by luccahuguet** [comment]
I give in, let's roll with a bash script

**Comment by luccahuguet** [comment]
this is the dumb version:

open_file.sh
```bash
#!/bin/sh

# Move focus to the next pane
zellij action focus-next-pane
zellij action write 27 # press esc
zellij action write-chars ":open $1"
zellij action write 13 # press enter
```

yazi.toml
```toml
# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
# yazelix v4
edit = [
  { exec = '~/.config/zellij/yazi/open_file.sh $1', desc = "Open File in a new pane" },
]

# yazelix v3
# edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
```
